# These are supported funding model platforms

# GitHub Sponsors
# github: [avilaops]

# Custom sponsor links (uncomment and update when available)
# custom: ['https://avila.inc/sponsor', 'https://roncavbudget.avila.inc/sponsor']

# Other platforms (uncomment and update when available)
# patreon: roncavbudget
# ko_fi: roncavbudget
# open_collective: roncavbudget
